version: '3'
services:
  db:
    container_name: pdamtb_db
    image: postgres:15.0-alpine
    restart: always
    ports: 
       - "5432:5432" 
    volumes:
       - $PWD/db-data:/var/lib/postgresql/data
    env_file:
       - './.env' 

